### ISSUE TITLE
Code style and contributing

### ISSUE THREAD

**Issue by ghost** [CodeforAustralia/public-site#4]
I'd like to send a bunch of PRs but am not sure of the accepted coding style, so I propose following [GitHub's Styleguide](https://github.com/styleguide/ruby).

**Comment by ghost** [comment]
Should probably add a CONTRIBUTING.md and a LICENSE.md too.

**Comment by cdaloisio** [comment]
@Soliah Not a problem. The site was put together really quickly so that we could get adequate marketing coverage before events that will be running in the coming months. Feel free to send through any PRs that you like :)
