### ISSUE TITLE
Goals for the public site

### ISSUE THREAD

**Issue by ghost** [CodeforAustralia/public-site#8]
What are the goals for the public site? I see that there is Rails admin and a bunch of stuff to do with projects and what not.

Should this really be part of the public site? I'd actually recommend using a static site generator to deal with content on http://codeforaustralia.org and place the Rails app behind a subdomain:
- programs.codeforaustralia.org for the incubator, fellowship etc
- secure.codeforaustralia.org things like donations, registering for a mailing list etc
- discuss.codeforaustralia.org [Discourse](discourse.org) forum for open discussion

The blog can be part of the main website statically generated as well. It can then be simply hosted on S3 for next to nothing.

Thoughts?

**Comment by CMCDragonkai** [comment]
If you guys decide to build a single page application, feel free to use https://snapsearch.io/ to make it indexable.

**Comment by cdaloisio** [comment]
@Soliah I like the idea! The public site is currently getting a complete redesign from some volunteers in Melbourne. I will raise this with them to take into consideration. We can then make some dev decisions once we get a look at the designs. It's currently hosted on a dev plan on Heroku so it's free for the moment anyways.
@CMCDragonkai Thanks will look into it :)
